/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sahir
 */
import java.io.*;
public class Location extends javax.swing.JFrame {

    /**
     * Creates new form Location
     */
    public String loc;
    File locate;
    public Location() {
        initComponents();
        setTitle("Location");
        try {
            locate = new File("Location.txt");
            if(!locate.exists())
                locate.createNewFile();
        }
        catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        GuindyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PotheriButton = new javax.swing.JButton();
        TambaramButton = new javax.swing.JButton();
        ChetpetButton = new javax.swing.JButton();
        EgmoreButton = new javax.swing.JButton();
        SaidapetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1121, 675));

        GuindyButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GuindyButton.setText("Guindy");
        GuindyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuindyButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("LOCATION");
        jLabel1.setMaximumSize(new java.awt.Dimension(104, 44));
        jLabel1.setMinimumSize(new java.awt.Dimension(104, 44));
        jLabel1.setPreferredSize(new java.awt.Dimension(104, 44));

        PotheriButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PotheriButton.setText("Potheri");
        PotheriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotheriButtonActionPerformed(evt);
            }
        });

        TambaramButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TambaramButton.setText("Tambaram");
        TambaramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambaramButtonActionPerformed(evt);
            }
        });

        ChetpetButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ChetpetButton.setText("Chetpet");
        ChetpetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChetpetButtonActionPerformed(evt);
            }
        });

        EgmoreButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EgmoreButton.setText("Egmore");
        EgmoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgmoreButtonActionPerformed(evt);
            }
        });

        SaidapetButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SaidapetButton.setText("Saidapet");
        SaidapetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidapetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(446, 446, 446))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GuindyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(PotheriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TambaramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EgmoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(ChetpetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(SaidapetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuindyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PotheriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambaramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EgmoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChetpetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaidapetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void WritetoFile(String location) {
        try {
            FileWriter fw = new FileWriter(locate);
            fw.write(location);
            fw.close();
        }
        catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    public void endLocation() {
        Symptoms s = new Symptoms();
        s.setVisible(true);
        this.setVisible(false);
    }
    
    private void GuindyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuindyButtonActionPerformed
        // TODO add your handling code here:
        loc = "Guindy";
        WritetoFile(loc);
        endLocation();
    }//GEN-LAST:event_GuindyButtonActionPerformed

    private void PotheriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotheriButtonActionPerformed
        // TODO add your handling code here:
        loc = "Potheri";
        WritetoFile(loc);
        endLocation();
    }//GEN-LAST:event_PotheriButtonActionPerformed

    private void TambaramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambaramButtonActionPerformed
        // TODO add your handling code here:
        loc = "Tambaram";
        WritetoFile(loc);
        endLocation();
    }//GEN-LAST:event_TambaramButtonActionPerformed

    private void EgmoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgmoreButtonActionPerformed
        // TODO add your handling code here:
        loc = "Egmore";
        WritetoFile(loc);
        endLocation();
    }//GEN-LAST:event_EgmoreButtonActionPerformed

    private void ChetpetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChetpetButtonActionPerformed
        // TODO add your handling code here:
        loc = "Chetpet";
        WritetoFile(loc);
        endLocation();
    }//GEN-LAST:event_ChetpetButtonActionPerformed

    private void SaidapetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidapetButtonActionPerformed
        // TODO add your handling code here:
        loc = "Saidapet";
        WritetoFile(loc);
        endLocation();
    }//GEN-LAST:event_SaidapetButtonActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChetpetButton;
    private javax.swing.JButton EgmoreButton;
    private javax.swing.JButton GuindyButton;
    private javax.swing.JButton PotheriButton;
    private javax.swing.JButton SaidapetButton;
    private javax.swing.JButton TambaramButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
