/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sahir
 */
import java.io.*;
import javax.swing.*;
import java.util.*;


public class Symptoms extends javax.swing.JFrame {

    /**
     * Creates new form Injury
     */
    String[] symptomStrings;
    File symptomFile,userSymptoms,reqDoctor;
    JComboBox[] SymptomBoxList;
    JLabel[] SymptomLabelList;
    JButton[] submitSymptom;
    String loc;
    int symptomNumber;
    Vector<String> symptomVector = new Vector<String>();
    public Symptoms() {
        initComponents();
        try {
            symptomFile = new File("SymptomList.txt");
            userSymptoms = new File("UserSymptoms.txt");
            loc = getLoc();
            loc = loc + "DoctorList.txt";
            reqDoctor = new File("RequiredDoctor.txt");
            if(!reqDoctor.exists())
                reqDoctor.createNewFile();
            if(!symptomFile.exists()) 
                symptomFile.createNewFile();
            if(!userSymptoms.exists())
                userSymptoms.createNewFile();
        }
        catch (Exception e) {
            System.out.println("File error: " + e);
        }
        initSymptomStrings();
        symptomNumber = 1;
        initComboBoxArray();
        hideSymptomList();
        initHideSubmitButton();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SymptomSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SymptomComboBox1 = new javax.swing.JComboBox<>();
        SymptomLabel1 = new javax.swing.JLabel();
        SymptomLabel3 = new javax.swing.JLabel();
        SymptomComboBox3 = new javax.swing.JComboBox<>();
        SymptomComboBox4 = new javax.swing.JComboBox<>();
        SymptomLabel4 = new javax.swing.JLabel();
        SymptomComboBox5 = new javax.swing.JComboBox<>();
        SymptomLabel5 = new javax.swing.JLabel();
        SymptomLabel6 = new javax.swing.JLabel();
        SymptomComboBox6 = new javax.swing.JComboBox<>();
        SymptomLabel7 = new javax.swing.JLabel();
        SymptomComboBox7 = new javax.swing.JComboBox<>();
        SymptomComboBox8 = new javax.swing.JComboBox<>();
        SymptomLabel8 = new javax.swing.JLabel();
        SymptomComboBox9 = new javax.swing.JComboBox<>();
        SymptomLabel9 = new javax.swing.JLabel();
        SymptomComboBox10 = new javax.swing.JComboBox<>();
        SymptomLabel10 = new javax.swing.JLabel();
        AddSymptom = new javax.swing.JButton();
        RemoveSymptom = new javax.swing.JButton();
        SymptomComboBox2 = new javax.swing.JComboBox<>();
        SymptomLabel2 = new javax.swing.JLabel();
        SubmitSymptom1 = new javax.swing.JButton();
        SubmitSymptom2 = new javax.swing.JButton();
        SubmitSymptom3 = new javax.swing.JButton();
        SubmitSymptom4 = new javax.swing.JButton();
        SubmitSymptom5 = new javax.swing.JButton();
        SubmitSymptom10 = new javax.swing.JButton();
        SubmitSymptom9 = new javax.swing.JButton();
        SubmitSymptom8 = new javax.swing.JButton();
        SubmitSymptom7 = new javax.swing.JButton();
        SubmitSymptom6 = new javax.swing.JButton();
        SymptomSubmitButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        SymptomSubmit.setText("Submit");
        SymptomSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomSubmitActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INJURY");

        SymptomComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox1ActionPerformed(evt);
            }
        });

        SymptomLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel1.setText("Select Injury");

        SymptomLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel3.setText("Select Injury");

        SymptomComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox3ActionPerformed(evt);
            }
        });

        SymptomComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox4ActionPerformed(evt);
            }
        });

        SymptomLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel4.setText("Select Injury");

        SymptomComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox5ActionPerformed(evt);
            }
        });

        SymptomLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel5.setText("Select Injury");

        SymptomLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel6.setText("Select Injury");

        SymptomComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox6ActionPerformed(evt);
            }
        });

        SymptomLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel7.setText("Select Injury");

        SymptomComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox7ActionPerformed(evt);
            }
        });

        SymptomComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox8ActionPerformed(evt);
            }
        });

        SymptomLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel8.setText("Select Injury");

        SymptomComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox9ActionPerformed(evt);
            }
        });

        SymptomLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel9.setText("Select Injury");

        SymptomComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox10ActionPerformed(evt);
            }
        });

        SymptomLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel10.setText("Select Injury");

        AddSymptom.setText("Add");
        AddSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSymptomActionPerformed(evt);
            }
        });

        RemoveSymptom.setText("Remove");
        RemoveSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSymptomActionPerformed(evt);
            }
        });

        SymptomComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SymptomComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomComboBox2ActionPerformed(evt);
            }
        });

        SymptomLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SymptomLabel2.setText("Select Injury");

        SubmitSymptom1.setText("Submit");
        SubmitSymptom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom1ActionPerformed(evt);
            }
        });

        SubmitSymptom2.setText("Submit");
        SubmitSymptom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom2ActionPerformed(evt);
            }
        });

        SubmitSymptom3.setText("Submit");
        SubmitSymptom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom3ActionPerformed(evt);
            }
        });

        SubmitSymptom4.setText("Submit");
        SubmitSymptom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom4ActionPerformed(evt);
            }
        });

        SubmitSymptom5.setText("Submit");
        SubmitSymptom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom5ActionPerformed(evt);
            }
        });

        SubmitSymptom10.setText("Submit");
        SubmitSymptom10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom10ActionPerformed(evt);
            }
        });

        SubmitSymptom9.setText("Submit");
        SubmitSymptom9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom9ActionPerformed(evt);
            }
        });

        SubmitSymptom8.setText("Submit");
        SubmitSymptom8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom8ActionPerformed(evt);
            }
        });

        SubmitSymptom7.setText("Submit");
        SubmitSymptom7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom7ActionPerformed(evt);
            }
        });

        SubmitSymptom6.setText("Submit");
        SubmitSymptom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSymptom6ActionPerformed(evt);
            }
        });

        SymptomSubmitButton.setText("Submit");
        SymptomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SymptomLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SymptomComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubmitSymptom10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(SymptomSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SymptomComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SymptomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitSymptom1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SymptomComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SymptomLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitSymptom2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SymptomComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SymptomLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitSymptom3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(RemoveSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitSymptom10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initSymptomStrings() {
        System.out.println("Getting Symptom Strings");
        symptomStrings = new String[38];
        try {
            BufferedReader br = new BufferedReader(new FileReader(symptomFile));
            String line; int i = 0;
            while((line = br.readLine()) != null) {
                symptomStrings[i] = line.trim();
                i++;
            }
        }
        catch (Exception e) {
            System.out.println("File error: " + e);
        }
        for(String str : symptomStrings) {
            System.out.println(str);
        }
    }
    
    public String getLoc() {
        String str = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader("Location.txt"));
            String line;
            while((line = br.readLine()) != null) {
                str = line.trim();
            }
        }
        catch (Exception e) {
            System.out.println("File error: " + e);
        }
        return str;
    }
    
    public void setSymptomVisibility() {
        System.out.println("symptom number: " + symptomNumber);
        for(int i = 0; i < SymptomBoxList.length; i++) {
            if(i < symptomNumber)
                this.SymptomBoxList[i].setVisible(true);
            else
                this.SymptomBoxList[i].setVisible(false);
        }
        
        for(int i = 0; i < SymptomLabelList.length; i++) {
            if(i < symptomNumber)
                this.SymptomLabelList[i].setVisible(true);
            else
                this.SymptomLabelList[i].setVisible(false);
        }
    }
    
    public void initComboBoxArray() {
        SymptomBoxList = new JComboBox[10];
        SymptomBoxList[0] = this.SymptomComboBox1;
        SymptomBoxList[1] = this.SymptomComboBox2;
        SymptomBoxList[2] = this.SymptomComboBox3;
        SymptomBoxList[3] = this.SymptomComboBox4;
        SymptomBoxList[4] = this.SymptomComboBox5;
        SymptomBoxList[5] = this.SymptomComboBox6;
        SymptomBoxList[6] = this.SymptomComboBox7;
        SymptomBoxList[7] = this.SymptomComboBox8;
        SymptomBoxList[8] = this.SymptomComboBox9;
        SymptomBoxList[9] = this.SymptomComboBox10;
        
        SymptomLabelList = new JLabel[10];
        SymptomLabelList[0] = this.SymptomLabel1;
        SymptomLabelList[1] = this.SymptomLabel2;
        SymptomLabelList[2] = this.SymptomLabel3;
        SymptomLabelList[3] = this.SymptomLabel4;
        SymptomLabelList[4] = this.SymptomLabel5;
        SymptomLabelList[5] = this.SymptomLabel6;
        SymptomLabelList[6] = this.SymptomLabel7;
        SymptomLabelList[7] = this.SymptomLabel8;
        SymptomLabelList[8] = this.SymptomLabel9;
        SymptomLabelList[9] = this.SymptomLabel10;
        
        /*
        this.SymptomComboBox1 = new JComboBox(symptomStrings);
        this.SymptomComboBox2 = new JComboBox(symptomStrings);
        this.SymptomComboBox3 = new JComboBox(symptomStrings);
        this.SymptomComboBox4 = new JComboBox(symptomStrings);
        this.SymptomComboBox5 = new JComboBox(symptomStrings);
        this.SymptomComboBox6 = new JComboBox(symptomStrings);
        this.SymptomComboBox7 = new JComboBox(symptomStrings);
        this.SymptomComboBox8 = new JComboBox(symptomStrings);
        this.SymptomComboBox9 = new JComboBox(symptomStrings);
        this.SymptomComboBox10 = new JComboBox(symptomStrings);
        */
        
        for(JComboBox jcb : SymptomBoxList) {
            jcb.removeAllItems();
            for(String str : symptomStrings)
                jcb.addItem(str);
        }
        
        System.out.println("Initializing JComboBox Array");
    }
    
    public void hideSymptomList() {
        for(int i = 1; i < SymptomBoxList.length; i++) {
            SymptomBoxList[i].setVisible(false);
            SymptomLabelList[i].setVisible(false);
        }
    }
    
    public void initHideSubmitButton() {
        submitSymptom = new JButton[10];
        submitSymptom[0] = this.SubmitSymptom1;
        submitSymptom[1] = this.SubmitSymptom2;
        submitSymptom[2] = this.SubmitSymptom3;
        submitSymptom[3] = this.SubmitSymptom4;
        submitSymptom[4] = this.SubmitSymptom5;
        submitSymptom[5] = this.SubmitSymptom6;
        submitSymptom[6] = this.SubmitSymptom7;
        submitSymptom[7] = this.SubmitSymptom8;
        submitSymptom[8] = this.SubmitSymptom9;
        submitSymptom[9] = this.SubmitSymptom10;
        for(JButton jb : submitSymptom)
            jb.setVisible(false);
    }
    
    public void writeSymptomsToFile() {
        try {
            PrintWriter pw = new PrintWriter(userSymptoms);
            for(String str : symptomVector) {
                pw.println(str);
            }
            pw.close();
        }
        catch (Exception e) {
            System.out.println("File error: " + e);
        }
        
    }
    
    public void writeDocRecommendation() {
        int doc[] = new int[7];
        String doctor[] = {"ENT", "Cardiologist", "Pulmonologist", "Physician", "Endocrinologist", "Orthopedist", "Oncologist"};
        //int ENT = 0, Cardio = 0, Pulmo = 0, Physi = 0, Endo = 0, Ortho = 0, Onco = 0;
        for(String str : symptomVector) {
            switch(str) {
                case "Cold":doc[0]+=2; doc[2]++; doc[3]++; break;
                case "Cough": doc[0] +=2; doc[2]++; doc[3]++; break;
                case "Fever": doc[0] += 2; doc[2]++; doc[3]++; break;
                case "Sore Throat": doc[0]+= 2; doc[2]++; doc[3]++; break;
                case "Swollen Tonsils":doc[0]+= 2; doc[2]++; doc[3]++; break;
                case "Nausea": doc[3]++; break;
                case "Vomiting": doc[3]++; break;
                case "Stomach Pain":doc[3]++; break;
                case "Indigestion":doc[3]++; break;
                case "Headache": doc[3]++;break;
                case "Diarrhoea": doc[3]++;break;
                case "Body Pain": doc[3]++;doc[5]+=5;break;
                case "Joint Pain": doc[3]++;doc[5]+=5;break;
                case "Growth on body":doc[6] += 100; break;
                case "Swollen Lymph Nodes": doc[0]++;break;
                case "Head Congestion":doc[3]++; doc[0]++;break;
                case "Blocked Sinuses": doc[3]++;doc[0]++;break;
                case "Fatigue": doc[3]++;break;
                case "Loss of Apetite":doc[3]++; doc[0]++;break;
                case "Frequent Thirst": doc[4]+=10;break;
                case "Frequent Urination": doc[4]+=10;break;
                case "Blurred Vision":doc[4]+=10; break;
                case "Excessive Hunger":doc[4]+=10; break;
                case "Mental Confusion": doc[3]++;break;
                case "Weight Loss": doc[3]++; doc[0]+=2;break;
                case "Rashes":doc[0]+=10; break;
                case "Chills": doc[0]+=10;break;
                case "Insomnia": doc[3]+=10;break;
                case "Dizziness":doc[3]++; break;
                case "Muscle Spasm":doc[3]+=10; break;
                case "Hallucination": doc[3]+=10;break;
                case "Aggression": doc[3]+=10;break;
                case "Chest Pain": doc[1]+=10;break;
                case "Shortness of Breath":doc[1]+=10; break;
                case "Swollen Extremities":doc[1]+=10; break;
                case "Abdominal Cramps":doc[3]++;doc[1]+=10; break;
                case "Dementia":doc[3]++; break;
                case "Amnesia": doc[3]++;break;
                
                    
            }
            int max = 0; int index = 0;
            
            for(int i = 0; i < doc.length; i++) {
                if(doc[i] > max) {
                    max = doc[i];
                    index = i;
                }
            }
            
            String d = doctor[index];
            
            try {
                PrintWriter pw = new PrintWriter(new FileWriter(reqDoctor));
                pw.println(d);
                pw.close();
                
            }
            catch (Exception e) {
                System.out.println("File error: " + e);
            }
            
            
        }
    }
    
    private void SymptomComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox1ActionPerformed

    private void SymptomComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox3ActionPerformed

    private void SymptomComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox4ActionPerformed

    private void SymptomComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox5ActionPerformed

    private void SymptomComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox6ActionPerformed

    private void SymptomComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox7ActionPerformed

    private void SymptomComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox8ActionPerformed

    private void SymptomComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox9ActionPerformed

    private void SymptomComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox10ActionPerformed

    private void SymptomComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomComboBox2ActionPerformed

    private void AddSymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSymptomActionPerformed
        // TODO add your handling code here:
        if(symptomNumber < 10) {
            symptomNumber += 1;
            setSymptomVisibility();
        }
    }//GEN-LAST:event_AddSymptomActionPerformed

    private void RemoveSymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveSymptomActionPerformed
        // TODO add your handling code here:
        if(symptomNumber > 1) {
            symptomNumber -= 1;
            setSymptomVisibility();
        }
    }//GEN-LAST:event_RemoveSymptomActionPerformed

    private void SymptomSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomSubmitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SymptomSubmitActionPerformed

    private void SubmitSymptom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom1ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox1.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom1ActionPerformed

    private void SubmitSymptom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom2ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox2.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom2ActionPerformed

    private void SubmitSymptom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom3ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox3.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom3ActionPerformed

    private void SubmitSymptom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom4ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox4.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom4ActionPerformed

    private void SubmitSymptom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom5ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox5.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom5ActionPerformed

    private void SubmitSymptom10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom10ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox10.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom10ActionPerformed

    private void SubmitSymptom9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom9ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox9.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom9ActionPerformed

    private void SubmitSymptom8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom8ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox8.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom8ActionPerformed

    private void SubmitSymptom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom7ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox7.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom7ActionPerformed

    private void SubmitSymptom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSymptom6ActionPerformed
        // TODO add your handling code here:
        int sel;
        sel = this.SymptomComboBox6.getSelectedIndex();
        symptomVector.add(symptomStrings[sel]);
    }//GEN-LAST:event_SubmitSymptom6ActionPerformed

    private void SymptomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomSubmitButtonActionPerformed
        // TODO add your handling code here:
        int i = 0;
        String symptomSubmit[] = new String[symptomNumber];
        for(JButton jb : submitSymptom) {
            if(i < symptomNumber)
                jb.doClick();
            i++;
        }
        writeSymptomsToFile();
        writeDocRecommendation();
        Doctor obj = new Doctor();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SymptomSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Symptoms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Symptoms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Symptoms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Symptoms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Symptoms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSymptom;
    private javax.swing.JButton RemoveSymptom;
    private javax.swing.JButton SubmitSymptom1;
    private javax.swing.JButton SubmitSymptom10;
    private javax.swing.JButton SubmitSymptom2;
    private javax.swing.JButton SubmitSymptom3;
    private javax.swing.JButton SubmitSymptom4;
    private javax.swing.JButton SubmitSymptom5;
    private javax.swing.JButton SubmitSymptom6;
    private javax.swing.JButton SubmitSymptom7;
    private javax.swing.JButton SubmitSymptom8;
    private javax.swing.JButton SubmitSymptom9;
    private javax.swing.JComboBox<String> SymptomComboBox1;
    private javax.swing.JComboBox<String> SymptomComboBox10;
    private javax.swing.JComboBox<String> SymptomComboBox2;
    private javax.swing.JComboBox<String> SymptomComboBox3;
    private javax.swing.JComboBox<String> SymptomComboBox4;
    private javax.swing.JComboBox<String> SymptomComboBox5;
    private javax.swing.JComboBox<String> SymptomComboBox6;
    private javax.swing.JComboBox<String> SymptomComboBox7;
    private javax.swing.JComboBox<String> SymptomComboBox8;
    private javax.swing.JComboBox<String> SymptomComboBox9;
    private javax.swing.JLabel SymptomLabel1;
    private javax.swing.JLabel SymptomLabel10;
    private javax.swing.JLabel SymptomLabel2;
    private javax.swing.JLabel SymptomLabel3;
    private javax.swing.JLabel SymptomLabel4;
    private javax.swing.JLabel SymptomLabel5;
    private javax.swing.JLabel SymptomLabel6;
    private javax.swing.JLabel SymptomLabel7;
    private javax.swing.JLabel SymptomLabel8;
    private javax.swing.JLabel SymptomLabel9;
    private javax.swing.JButton SymptomSubmit;
    private javax.swing.JButton SymptomSubmitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
